version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - ./.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - default
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
    name: defenders-db